spring:
  application:
    name: CONTENT-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:3344/MyContent
      database: MyContent
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue:
      initiate-content: q.content-space-allocator
      dlq: q.DLQ
    exchange:
      aws-store: AWS-Storage-Service-Exchange
      dlx: DLX-Exchange
    route-key:
      space-allocate: allocate-content-space

server:
  port: 8082

  jpa:
    show-sql: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#  instance:
#    prefer-ip-address: false
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

#service path
internal:
  service:
    subscription:
      path: /user/{user_id}/subscriptions
      domain: http://127.0.0.1:8084
