spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      globalcors:
#        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - OPTION
            allowedHeaders: "*"
            allowCredentials: "true"
      discovery:
        locator:
          enabled: true
          lower-case-service-id : true


server:
  port: 8080
  max-http-header-size: 16384

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: false

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty.http.client: DEBUG
    reactor:
      netty:
        http:
          server: DEBUG

