server:
  port: 9090
spring:
  application:
    name: AWS-SERVICE
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3333/mydb
    username: root
    password: pwd
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

aws:
  accessKeyId: AKIAYG42OWDMXDKPHUVY
  secretkey: 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
  s3:
    bucketname: myfreebucket122343
    region: ap-south-1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


